language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -U pip setuptools
  - pip install -e .
  - pip install -r requirements-test.txt
  - pip install coveralls nose coverage httpretty
script: nosetests --with-coverage --cover-package=messytables
after_success:
  - coveralls
